plugin "cocoapods-binary-cache"

config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks"
    }
  },
  prebuild_config: "Debug",
  device_build_enabled: true,
  xcframework: true
)

def binary_pod(name, *args)
  pod name, args, :binary => true
end

platform :ios, '13.0'

target 'PictureDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PictureDiary
  
  # Rx
  binary_pod 'RxSwift', '~> 6.0'
  binary_pod 'RxCocoa', '~> 6.0'
  binary_pod 'RxGesture', '~> 4.0'

  # 🦴 RIBs
  pod 'RIBs', :git => 'git@github.com:uber/RIBs.git', :binary => true

  # 📸 Images
  binary_pod 'Kingfisher', '~> 7.0'

  # ⚡️ Moya
  binary_pod 'Moya', '~> 15.0'
  binary_pod 'Moya/RxSwift', '~> 15.0'

  # 🎨 UI
  binary_pod 'SnapKit', '~> 5.6.0'
  binary_pod 'IQKeyboardManagerSwift'
  pod 'lottie-ios', :git => 'git@github.com:airbnb/lottie-ios.git', :binary => true

  # 🛠 Utils
  binary_pod 'Then'
  binary_pod 'SwiftKeychainWrapper'
  
  # OAuth
  binary_pod 'RxKakaoSDKUser'
  binary_pod 'GoogleSignIn'

end
